### ISSUE TITLE
Metadata edit view is broken

### ISSUE THREAD

**Issue by lagoan** [arcualberta/Catfish#14]
When loading the view "/manager/metadata/edit" the application gives a compilation error.

![screen shot 2017-09-01 at 11 04 49 am](https://user-images.githubusercontent.com/1537909/29980085-6756179e-8f05-11e7-8060-975ad93e949d.png)

**Comment by lagoan** [comment]
@melaniar : "the error from the metadata/edit page is because it still refer to MetadataDefinition model that we are no longer using"

**Comment by melaniar** [comment]
I modified the metadata/edit get method to return MetadataSet object instead and temporary redirect to EditTest page
